version: '2'
services:
  db:
      image: mongo
      volumes:
        - "/data/mongodb:/data/db"
      restart: always

  appjava:
      build: ./todolistapp
      depends_on:
        - db
      image: todolist:latest
      volumes:
        - "./todolistapp:/app/"
      links:
        - db
      ports:
        - "8080:8080"
      restart: always
